// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7F8ewUyVHZl391usFY5bRWotHSbDX_o',
    appId: '1:723224171655:web:c7655960175d488f149422',
    messagingSenderId: '723224171655',
    projectId: 'fasum-app-7f36e',
    authDomain: 'fasum-app-7f36e.firebaseapp.com',
    storageBucket: 'fasum-app-7f36e.firebasestorage.app',
    measurementId: 'G-RNZM89PLDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFROfwt9Rmm3F4M35kG-uE4SrzcUR6PB4',
    appId: '1:723224171655:android:f34c6dce396aabce149422',
    messagingSenderId: '723224171655',
    projectId: 'fasum-app-7f36e',
    storageBucket: 'fasum-app-7f36e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZMAZDU4lqROqUwYH_4rcWt8ldzc3sVk',
    appId: '1:723224171655:ios:cebe47ecf58b932f149422',
    messagingSenderId: '723224171655',
    projectId: 'fasum-app-7f36e',
    storageBucket: 'fasum-app-7f36e.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZMAZDU4lqROqUwYH_4rcWt8ldzc3sVk',
    appId: '1:723224171655:ios:cebe47ecf58b932f149422',
    messagingSenderId: '723224171655',
    projectId: 'fasum-app-7f36e',
    storageBucket: 'fasum-app-7f36e.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_7F8ewUyVHZl391usFY5bRWotHSbDX_o',
    appId: '1:723224171655:web:70c2f90af4dc0ed0149422',
    messagingSenderId: '723224171655',
    projectId: 'fasum-app-7f36e',
    authDomain: 'fasum-app-7f36e.firebaseapp.com',
    storageBucket: 'fasum-app-7f36e.firebasestorage.app',
    measurementId: 'G-FSX0VT1PK4',
  );
}
